// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR4WqSOBVkRln_GOohrUwa6pJpXFwnnp8',
    appId: '1:698016856565:web:be562c71758615310188bc',
    messagingSenderId: '698016856565',
    projectId: 'joflex-bf5f3',
    authDomain: 'joflex-bf5f3.firebaseapp.com',
    storageBucket: 'joflex-bf5f3.appspot.com',
    measurementId: 'G-XMRTM78P6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwautsNtcYHGQZgJZH0Ncd8DuTvOzyNg',
    appId: '1:698016856565:android:eababa34bf33bcb30188bc',
    messagingSenderId: '698016856565',
    projectId: 'joflex-bf5f3',
    storageBucket: 'joflex-bf5f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9qTi3cKhTUaerLl5Yv1vHLsoxb6te1k',
    appId: '1:698016856565:ios:cb767c68096dc58a0188bc',
    messagingSenderId: '698016856565',
    projectId: 'joflex-bf5f3',
    storageBucket: 'joflex-bf5f3.appspot.com',
    iosBundleId: 'com.example.joflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9qTi3cKhTUaerLl5Yv1vHLsoxb6te1k',
    appId: '1:698016856565:ios:31e064eaee1c28220188bc',
    messagingSenderId: '698016856565',
    projectId: 'joflex-bf5f3',
    storageBucket: 'joflex-bf5f3.appspot.com',
    iosBundleId: 'com.example.joflex.RunnerTests',
  );
}
